name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/project2-frontend:dev
    
    steps:
      - name: Pull docker image
        run: docker pull $DOCKER_REPO
      - name: Delete old docker container
        run: docker rm -f cicd-pipeline-container || true
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name cicd-pipeline-container $DOCKER_REPO
