name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - features
    # paths

jobs:
  test_and_build:
    name: Run tests and build container image
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/project2-frontend:dev
    
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      # Clean install
      - run: npm ci
      - run: npm test
      
      - name: Run tests and build vite project with production environment variables
        run: npm run build
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        continue-on-error: false
      
      - name: Create updated image build
        run: |
          docker build . -t $DOCKER_REPO
          docker push $DOCKER_REPO

  deploy:
    needs: test_and_build
    runs-on: [self-hosted, frontend]

    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/project2-frontend:dev
    
    steps:
      - name: Pull docker image
        run: docker pull $DOCKER_REPO
      - name: Delete old docker container
        run: docker rm -f cicd-pipeline-container || true
      - name: Run docker container
        run: docker run -d -p 8080:3000 --name cicd-pipeline-container $DOCKER_REPO